language: node_js
node_js:
  - '6.4.0'
notifications:
  email: false
before_install:
  - travis_retry nvm install 6.4.0
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm install request;
      npm run update-package;
    fi
env:
  global:
  - secure: k0uMlCKWtC0elOcpIHk9W6+YIKr+WmUUmhQK3csAuYJDaq+sSObTKm6Hk6cjN1dYUbo2zgfOPiR+7YpFOFDh5fETNo+HUtDb15B6N80vgquUhNQMn6htqYk32xYawtxfeQmbEiaf2PcKLSA7EVpEniSN0ePYhAz4qBhY//beQuY=
  - secure: kvhzrtoklquMdydUkwYrwrBT7LXrVPXbcJ3I3RcKJ5l7jiuAdGoW/VKd2lcqZmiRHmjI8pmqLaCU1SToW317a8BSnUMm995YNuIn+YEocYWz+CXg7ClWwBpqGn0etVGWaAe5NTFnB+iKiTsb6C7lemrDY67FzjyJ6vahSXX6oHk=
script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm run get-test-utils && npm run test ; npm run lint ; npm run report;
    else
      npm run merge;
    fi
